services:
  db:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: khai
      POSTGRES_DB: movie_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - movix_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    environment:
      - AI_SERVICE_URL=http://ai_engine:8000
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npm run build && npm start"
    depends_on:
      db:
        condition: service_healthy
      ai_engine:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - movix_network

  redis:
    image: redis:alpine
    container_name: movix-be-redis
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - movix_network

  ai_engine:
    build:
      context: ./recommendation-engine
    ports:
      - "8000:8000"
    volumes:
      - ./recommendation-engine:/app
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - movix_network

volumes:
  db_data:

networks:
  movix_network:
    driver: bridge
